name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Style (non-blocking)
        run: |
          python -m pip install ruff
          ruff format .
          ruff check . --exit-zero   # never fail on style

      - name: Sanity (must pass): Python compiles
        run: |
          pyfiles="$(git ls-files '*.py' || true)"
          if [ -n "$pyfiles" ]; then python -m py_compile $pyfiles; fi
